name: Deploy to Mini PC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest code
        run: |
          cd ~/AssetManagementProject
          git pull

      - name: Build and restart containers
        run: |
          cd ~/AssetManagementProject
          docker compose up -d --build